version: '3'

services:
  web:
    build: .
    ports:
      - '3000:3000'
    volumes: 
      - '.:/usr/src/app'
    tty: true
    stdin_open: true
    command: bash -c "rm -f tmp/pids/server.pid && bundle install && bundle exec rails s -p 3000 -b '0.0.0.0'"
    # db作成後にコンテナ作成
    depends_on: 
      - db

  db:
    image: postgres:13
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password

  pgadmin:
    image: dpage/pgadmin4
    volumes:
      - ./pgadmin:/var/lib/pgadmin
    ports:
      - "80:80"
      - "443:443"
    environment:
        PGADMIN_DEFAULT_EMAIL: "pg@example.com"
        PGADMIN_DEFAULT_PASSWORD: "pg-password"
